spring.application.name=api-gateway
server.port = 8080

#Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

#Enable Service discovery
spring.cloud.gateway.server.webflux.discovery.locator.enabled=true
spring.cloud.gateway.server.webflux.discovery.locator.lower-case-service-id=true

#twillio
twilio.account.sid=YOUR_ACCOUNT_SID
twilio.auth.token=YOUR_AUTH_TOKEN
twilio.phone.number=YOUR_TWILIO_PHONE_NUMBER